/**
 * PostmanGenerator — generates Postman Collection v2.1
 * from inferred API endpoints, compatible with Postman import.
 */

import type { APIEndpoint, JSONSchema, JSONSchemaProperty } from '../types';

export interface PostmanCollection {
  info: {
    name: string;
    description?: string;
    schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json';
  };
  item: PostmanItem[];
  variable?: PostmanVariable[];
}

interface PostmanItem {
  name: string;
  item?: PostmanItem[];
  request?: PostmanRequest;
  response?: any[];
}

interface PostmanRequest {
  method: string;
  header: { key: string; value: string; description?: string }[];
  url: PostmanUrl;
  body?: PostmanBody;
  description?: string;
}

interface PostmanUrl {
  raw: string;
  host: string[];
  port?: string;
  path: string[];
  query?: { key: string; value: string; description?: string }[];
  variable?: { key: string; value: string; description?: string }[];
}

interface PostmanBody {
  mode: 'raw' | 'urlencoded' | 'formdata';
  raw?: string;
  options?: { raw: { language: string } };
}

interface PostmanVariable {
  key: string;
  value: string;
  type: string;
}

export class PostmanGenerator {
  private baseUrl: string;

  constructor(baseUrl: string = 'http://localhost:8080') {
    this.baseUrl = baseUrl;
  }

  generate(endpoints: APIEndpoint[]): PostmanCollection {
    const grouped = this.groupByTag(endpoints);
    const items: PostmanItem[] = [];

    for (const [tag, eps] of Object.entries(grouped)) {
      if (eps.length === 1) {
        items.push(this.buildItem(eps[0]));
      } else {
        items.push({
          name: tag,
          item: eps.map(ep => this.buildItem(ep)),
        });
      }
    }

    return {
      info: {
        name: 'Auto-generated API Collection',
        description: 'Generated by GrapesJS API Doc Plugin',
        schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
      },
      item: items,
      variable: [
        { key: 'baseUrl', value: this.baseUrl, type: 'string' },
      ],
    };
  }

  private buildItem(ep: APIEndpoint): PostmanItem {
    const url = this.buildUrl(ep);
    const request: PostmanRequest = {
      method: ep.method,
      header: [
        { key: 'Content-Type', value: 'application/json' },
        { key: 'Accept', value: 'application/json' },
      ],
      url,
      description: `${ep.summary}\n\n${ep.description || ''}`,
    };

    // Request body
    if (ep.requestSchema) {
      request.body = {
        mode: 'raw',
        raw: JSON.stringify(this.schemaToExample(ep.requestSchema), null, 2),
        options: { raw: { language: 'json' } },
      };
    }

    return {
      name: `${ep.method} ${ep.summary || ep.path}`,
      request,
    };
  }

  private buildUrl(ep: APIEndpoint): PostmanUrl {
    // Parse base URL
    let urlObj: URL;
    try {
      urlObj = new URL(this.baseUrl);
    } catch {
      urlObj = new URL('http://localhost:8080');
    }

    const host = [urlObj.hostname];
    if (urlObj.port) host.push(urlObj.port);

    const port = urlObj.port || undefined;

    // Parse path — strip /api prefix for path segments
    const cleanPath = ep.path.replace(/^\/api\/?/, '');
    const pathSegments = cleanPath.split('/').filter(Boolean);

    // Replace {param} with :param (Postman convention)
    const pmPath = pathSegments.map(s => s.startsWith('{') ? `:${s.slice(1, -1)}` : s);

    const raw = `${this.baseUrl}${ep.path}`;

    const url: PostmanUrl = {
      raw,
      host,
      port,
      path: pmPath,
    };

    // Query parameters
    if (ep.queryParams.length > 0) {
      url.query = ep.queryParams.map(q => ({
        key: q.name,
        value: q.required ? '' : '',
        description: q.description,
      }));
    }

    // Path variables
    if (ep.pathParams.length > 0) {
      url.variable = ep.pathParams.map(p => ({
        key: p.name,
        value: p.type === 'number' ? '1' : 'example',
        description: p.description,
      }));
    }

    return url;
  }

  private groupByTag(endpoints: APIEndpoint[]): Record<string, APIEndpoint[]> {
    const groups: Record<string, APIEndpoint[]> = {};
    for (const ep of endpoints) {
      const tag = ep.tags[0] || 'Default';
      if (!groups[tag]) groups[tag] = [];
      groups[tag].push(ep);
    }
    return groups;
  }

  private schemaToExample(schema: JSONSchema): any {
    if (schema.example !== undefined) return schema.example;

    switch (schema.type) {
      case 'object':
        return this.objectToExample(schema);
      case 'array':
        return schema.items ? [this.schemaToExample(schema.items)] : [];
      case 'string':
        return this.stringExample(schema);
      case 'number':
      case 'integer':
        return 0;
      case 'boolean':
        return false;
      default:
        return null;
    }
  }

  private objectToExample(schema: JSONSchema): Record<string, any> {
    const obj: Record<string, any> = {};
    if (!schema.properties) return obj;

    for (const [key, prop] of Object.entries(schema.properties)) {
      if (prop.example !== undefined) {
        obj[key] = prop.example;
      } else if (prop.enum && prop.enum.length > 0) {
        obj[key] = prop.enum[0];
      } else {
        obj[key] = this.propToExample(key, prop);
      }
    }

    return obj;
  }

  private stringExample(schema: JSONSchema): string {
    if (schema.format === 'email') return 'user@example.com';
    if (schema.format === 'date-time') return new Date().toISOString();
    if (schema.format === 'date') return new Date().toISOString().split('T')[0];
    if (schema.format === 'uri') return 'https://example.com';
    if (schema.format === 'password') return '******';
    return '';
  }

  private propToExample(key: string, prop: JSONSchemaProperty): any {
    const lower = key.toLowerCase();

    if (lower === 'id' || lower.endsWith('id')) return 1;
    if (lower === 'username' || lower === 'name') return '示例名称';
    if (lower === 'email') return 'user@example.com';
    if (lower === 'phone' || lower === 'mobile') return '13800138000';
    if (lower === 'password') return '******';
    if (lower === 'status' || lower === 'enabled') return 1;
    if (lower === 'code') return 200;
    if (lower === 'message') return 'ok';
    if (lower === 'total') return 100;
    if (lower === 'page') return 1;
    if (lower === 'pagesize') return 20;
    if (lower === 'count' || lower === 'stock') return 50;
    if (lower === 'amount' || lower === 'price') return 99.99;
    if (lower === 'avatar') return 'https://via.placeholder.com/150';
    if (lower === 'title') return '示例标题';
    if (lower === 'url' || lower === 'website' || lower === 'link') return 'https://example.com';
    if (lower === 'createdat' || lower === 'updatedat') return new Date().toISOString();

    if (prop.type === 'number' || prop.type === 'integer') return 0;
    if (prop.type === 'boolean') return false;
    if (prop.type === 'string') return '';

    return null;
  }
}
